### ISSUE TITLE
PMD repo Distribution implementation Pt 1.

### ISSUE THREAD

**Issue by nimshi89** [GSS-Cogs/csvcubed-pmd#19]
The changes in the repo would focus on the reading of the data without changing the output, which has to follow the syntax supported on pmd currently. Backward compatibility has to be supported so it can read from the shapes we currently output and also from the new shapes(
the one with the dcat:Dataset and the dcat:Distribution).

_get_catalog_entry_from_dcat_dataset
Take the dataset info from the isDistributionof attribute

Add pmdcat_distribution = pmdcat.Distribution(str(record[“distribution”]))
Add the attributes os the distribution class

_delete_existing_dcat_metadata
Uses two functions

_delete_existing_dcat_dataset_metadata

Modify to query for the data coming from the Distribution class

_set_pmdcat_type_on_dataset_contents

This function might need change

**Testing

Testing regarding the repo might need changes to controbute for the Distribution class. 

If you find the ticket contains any additional work the create a follow up Pt 2 ticket.

**Comment by CharlesRendle** [comment]
Removing myself from this ticket before leaving and moving it back into the sprint backlog.|

This ticket was blocked for a while because we needed to rewrite the release procedures in csvcubed-models (so that we could have access to the new `Distribution` class and in csvcubed-pmd itself so that the changes from this ticket can be released.

The work completed so far looks like it follows the recommended changes as above but these were all implemented blindly without having access to the `Distribution`. Also drawing attention to [this change](https://github.com/GSS-Cogs/csvcubed-pmd/pull/18/files#diff-c56034a416c664b8e259eb704e2ed0258760729f9bde2592fa3eba636c891b9cR101-R104) where there is uncertainty around adding the distribution to the `Dataset` class.

My recommendation for picking up this ticket is to begin with a test that will demonstrate the output structure we currently have and start changing things to see what effect it has on the output structure.
